### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by AiMijie** [HKUNLP/icl-ceil#3]
When running the script "run_epr.sh" with smcalflow, I suffer this problem when it came to scorer.py.

**Comment by jiacheng-ye** [comment]
Thanks for your question, could you provide the full error output?

**Comment by AiMijie** [comment]
Thank you for your reply. I've solved it. If there is any new problem, I will consult you again. Thanks again.

**Comment by DHdroid** [comment]
@AiMijie How did you solve the issue? I've encountered the same error.
